# Generated by Django 4.0.5 on 2022-06-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('photo', models.CharField(default='/carpool/assets/profile/avatar.png', max_length=100)),
                ('driver_license_number', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11)),
                ('is_driver', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=400)),
                ('rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=400)),
                ('days', models.IntegerField()),
                ('free_seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carona_as_dest_addr', to='carpool.address')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carona_owned', to='carpool.profile')),
                ('passengers', models.ManyToManyField(blank=True, related_name='caronas', to='carpool.profile')),
                ('start_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carona_as_start_addr', to='carpool.address')),
            ],
        ),
    ]
