# Generated by Django 4.0.5 on 2022-06-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=400)),
                ('days', models.IntegerField()),
                ('free_seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpool_as_dest_addr', to='carpool.address')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpool_owned', to='carpool.profile')),
                ('passengers', models.ManyToManyField(blank=True, related_name='carpool', to='carpool.profile')),
                ('start_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpool_as_start_addr', to='carpool.address')),
            ],
        ),
        migrations.DeleteModel(
            name='Carona',
        ),
    ]
